version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: yozuru-db
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
